version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "every other week"
  - package-ecosystem: "npm"
    directory: "/code/src/AttendeeSite"
    schedule:
      interval: "daily"
